#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="${REPO_DIR:-${HOME}/upaiego-management}"
DOCS="${REPO_DIR}/docs"
SUPABASE_DIR="${HOME}/supabase/docker"

ORDER=(
  ROLE_SYSTEM_MIGRATION.sql
  GROUP_TOPICS_BUSINESS_MIGRATION.sql
  GROUP_WORK_GROUPS_RLS_FIX.sql
  PROFILES_GROUP_PEER_SELECT.sql
  SCENE_BUSINESS_ASSIGNMENT_MIGRATION.sql
  PARTY_DEMAND_DEVICE_TYPE_MIGRATION.sql
  SCENE_TASKS_ADMIN_POSITION_BIND_MIGRATION.sql
  SCENE_TASKS_BATCH_GENERATION_MIGRATION.sql
  MANUAL_TRACKED_DEVICES_MIGRATION.sql
  EXTERNAL_DEVICE_STATUS_MIGRATION.sql
  ADMIN_KPIS_ROLE_AND_PERIOD.sql
  ADMIN_KPIS_METRIC_KEYS.sql
  USER_ACCOUNT_DELETE_MIGRATION.sql
  PHONE_REGISTRATION_MIGRATION.sql
  REGISTRATION_INVITE_LOOKUP.sql
  REGISTRATION_SIGNUP_FIX.sql
  REGISTRATION_GROUP_CODE_ENFORCE.sql
  PROFILES_CONTACT_BACKFILL.sql
  BOUNTY_MIGRATION.sql
  BOUNTY_RPC_FIX.sql
  BOUNTY_DAILY_CLAIM_LIMIT.sql
  BOUNTY_OPERATOR_AUDIT_MIGRATION.sql
  BOUNTY_DEVICE_SETTLEMENT_V2.sql
  BOUNTY_SETTLE_RETURN_SPLIT.sql
  DEVICE_ASSIGNMENT_OFFLINE_MIGRATION.sql
  EXECUTOR_SETTLEMENT_MIGRATION.sql
  MANUAL_TRACKED_DEVICES_GROUP_SCOPE_FIX.sql
  ADMIN_DASHBOARD_MIGRATION.sql
  SCENE_MACRO_HIERARCHY_MIGRATION.sql
  SCENE_MACRO_PANORAMA_MIGRATION.sql
  SCENE_MACRO_CONTACT_MIGRATION.sql
  COLLECTION_SHIFT_MIGRATION.sql
  MANUAL_DEVICE_PUBLIC_CODE_TRIGGER_FIX.sql
  MANUAL_DEVICE_RLS_FIX.sql
  MANUAL_DEVICE_RANDOM_PREFIX_MIGRATION.sql
  AGENT_INBOX_MIGRATION.sql
  AGENT_BROADCAST_ADMIN_ONLY.sql
  AGENT_GROUP_RULES_MIGRATION.sql
  AGENT_CHAT_HISTORY_MIGRATION.sql
)

cd "${SUPABASE_DIR}"

for f in "${ORDER[@]}"; do
  path="${DOCS}/${f}"
  if [[ ! -f "${path}" ]]; then
    echo "SKIP (not found): ${f}"
    continue
  fi
  echo "==> ${f}"
  docker compose exec -T db psql -U postgres -d postgres -v ON_ERROR_STOP=1 < "${path}"
done

echo "All migrations applied."
