#!/usr/bin/env python3
"""Generate MULTI_ROLE_FUNCTIONS_PATCH.sql and MULTI_ROLE_RLS_PATCH.sql from schema.sql."""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMA = REPO / "schema.sql"
EXTRA_SQL = [
    REPO / "docs" / "MANUAL_DEVICE_EXECUTOR_ASSIGN_MIGRATION.sql",
]
OUT_FUNCTIONS = REPO / "docs" / "MULTI_ROLE_FUNCTIONS_PATCH.sql"
OUT_RLS = REPO / "docs" / "MULTI_ROLE_RLS_PATCH.sql"

ROLE_SINGLE = [
    "admin",
    "device_operator",
    "scene_operator",
    "collection_executor",
]

POLICY_RE = re.compile(
    r'CREATE POLICY "([^"]+)" ON (?:"([^"]+)"\.)?"([^"]+)"([\s\S]*?);',
    re.MULTILINE,
)


def patch_text(text: str) -> str:
    if "current_profile_role" not in text and "p.role =" not in text:
        return text

    out = text

    # Normalize quoted function name variants
    out = re.sub(
        r'"public"\."current_profile_role"\(\)',
        "public.current_profile_role()",
        out,
        flags=re.IGNORECASE,
    )
    out = re.sub(
        r'public\."current_profile_role"\(\)',
        "public.current_profile_role()",
        out,
        flags=re.IGNORECASE,
    )

    for op in ("NOT IN", "IN"):
        out = re.sub(
            rf"public\.current_profile_role\(\)\s+{op}\s*\(([^)]+)\)",
            lambda m, op=op: (
                f"NOT public.has_any_profile_role(ARRAY[{m.group(1)}])"
                if op == "NOT IN"
                else f"public.has_any_profile_role(ARRAY[{m.group(1)}])"
            ),
            out,
            flags=re.IGNORECASE,
        )

    def repl_any(m: re.Match[str]) -> str:
        inner = m.group(1)
        roles = re.findall(r"'([^']+)'", inner)
        if not roles:
            return m.group(0)
        arr = ", ".join(f"'{r}'" for r in roles)
        return f"public.has_any_profile_role(ARRAY[{arr}])"

    out = re.sub(
        r"public\.current_profile_role\(\)\s*=\s*ANY\s*\(\s*ARRAY\[([^\]]+)\]\s*\)",
        repl_any,
        out,
        flags=re.IGNORECASE,
    )

    for op in ("<>", "!="):
        for role in ROLE_SINGLE:
            out = out.replace(
                f"public.current_profile_role() {op} '{role}'",
                f"NOT public.has_profile_role('{role}')",
            )

    for role in ROLE_SINGLE:
        out = out.replace(
            f"public.current_profile_role() = '{role}'",
            f"public.has_profile_role('{role}')",
        )

    for role in ROLE_SINGLE:
        out = re.sub(
            rf"\bp\.role\s*=\s*'{role}'",
            f"'{role}' = ANY(COALESCE(p.roles, ARRAY[p.role]))",
            out,
        )

    out = re.sub(
        r"(public\.has_(?:profile_role|any_profile_role)\([^)]+\))::\"text\"",
        r"\1",
        out,
    )

    return out


def extract_functions(sql: str) -> list[tuple[str, str]]:
    pattern = re.compile(
        r"(CREATE OR REPLACE FUNCTION[\s\S]*?\$\$;)",
        re.MULTILINE,
    )
    results: list[tuple[str, str]] = []
    seen: set[str] = set()
    for m in pattern.finditer(sql):
        block = m.group(1)
        if "current_profile_role" not in block and not re.search(r"\bp\.role\s*=", block):
            continue
        name_m = re.search(r'FUNCTION\s+"?public"?\.?"?(\w+)"?', block)
        name = name_m.group(1) if name_m else "unknown"
        if name in seen:
            continue
        seen.add(name)
        results.append((name, block))
    return results


def extract_policies(sql: str) -> list[tuple[str, str, str, str]]:
    """Returns (policy_name, schema, table, full_create_stmt)."""
    out: list[tuple[str, str, str, str]] = []
    for m in POLICY_RE.finditer(sql):
        policy_name, schema, table, rest = m.group(1), m.group(2) or "public", m.group(3), m.group(4)
        full = f'CREATE POLICY "{policy_name}" ON "{schema}"."{table}"{rest};'
        if "current_profile_role" in full or '"current_profile_role"' in full:
            out.append((policy_name, schema, table, full))
    return out


def main() -> int:
    if not SCHEMA.exists():
        print(f"Missing {SCHEMA}")
        return 1

    sql_parts = [SCHEMA.read_text(encoding="utf-8")]
    for p in EXTRA_SQL:
        if p.exists():
            sql_parts.append(p.read_text(encoding="utf-8"))
    combined = "\n".join(sql_parts)

    funcs = extract_functions(combined)
    patched_funcs: list[str] = []
    for _name, block in funcs:
        new_block = patch_text(block)
        if new_block != block:
            patched_funcs.append(new_block)

    fn_header = """-- AUTO-GENERATED by scripts/generate_multi_role_patch.py — do not edit by hand
-- Patches public functions that use current_profile_role() or profiles.role single checks.

"""
    OUT_FUNCTIONS.write_text(
        fn_header + "\n\n".join(patched_funcs) + "\n\nNOTIFY pgrst, 'reload schema';\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(patched_funcs)} patched functions to {OUT_FUNCTIONS}")

    policies = extract_policies(SCHEMA.read_text(encoding="utf-8"))
    rls_lines = [
        "-- AUTO-GENERATED by scripts/generate_multi_role_patch.py — do not edit by hand",
        "-- RLS: current_profile_role() → has_profile_role / has_any_profile_role",
        "",
    ]
    for policy_name, schema, table, full in policies:
        patched = patch_text(full)
        if "has_profile_role" not in patched and "has_any_profile_role" not in patched:
            continue
        rls_lines.append(f'DROP POLICY IF EXISTS "{policy_name}" ON "{schema}"."{table}";')
        rls_lines.append(patched)
        rls_lines.append("")

    rls_lines.append("NOTIFY pgrst, 'reload schema';")
    OUT_RLS.write_text("\n".join(rls_lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(policies)} patched policies to {OUT_RLS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
