-- AUTO-GENERATED by scripts/generate_multi_role_patch.py — do not edit by hand
-- Patches public functions that use current_profile_role() or profiles.role single checks.

CREATE OR REPLACE FUNCTION "public"."_assert_operator_can_settle_claim"("p_claim_id" "uuid") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
BEGIN
  IF NOT public.has_any_profile_role(ARRAY['device_operator', 'admin']) THEN
    RAISE EXCEPTION 'device_operator or admin only';
  END IF;
  v_group := public._bounty_group_id_for_claim(p_claim_id);
  IF v_group IS NULL OR NOT public.policy_work_group_accessible(v_group) THEN
    RAISE EXCEPTION 'claim not in accessible group';
  END IF;
  IF public.has_profile_role('device_operator')
     AND NOT public._profile_is_device_operator_in_group(auth.uid(), v_group) THEN
    RAISE EXCEPTION 'not a device operator in this group';
  END IF;
  RETURN v_group;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."_assert_operator_in_claim_group"("p_claim_id" "uuid") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
BEGIN
  IF NOT public.has_any_profile_role(ARRAY['device_operator', 'admin']) THEN
    RAISE EXCEPTION 'device_operator or admin only';
  END IF;
  v_group := public._bounty_group_id_for_claim(p_claim_id);
  IF v_group IS NULL OR NOT public.policy_work_group_accessible(v_group) THEN
    RAISE EXCEPTION 'claim not in accessible group';
  END IF;
  IF public.has_profile_role('device_operator')
     AND NOT public._profile_is_device_operator_in_group(auth.uid(), v_group) THEN
    RAISE EXCEPTION 'not a device operator in this group';
  END IF;
  RETURN v_group;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."_profile_is_device_operator_in_group"("p_user_id" "uuid", "p_group_id" "uuid") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.group_members gm ON gm.user_id = p.id
    WHERE p.id = p_user_id
      AND 'device_operator' = ANY(COALESCE(p.roles, ARRAY[p.role]))
      AND gm.group_id = p_group_id
      AND gm.membership_status = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION "public"."abandon_bounty_claim"("p_claim_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_claim public.bounty_claims;
BEGIN
  SELECT * INTO v_claim FROM public.bounty_claims WHERE id = p_claim_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim not found';
  END IF;
  IF v_claim.executor_id <> auth.uid() THEN
    RAISE EXCEPTION 'not your claim';
  END IF;
  IF NOT public.has_profile_role('collection_executor') THEN
    RAISE EXCEPTION 'collection_executor only';
  END IF;
  PERFORM public._finalize_bounty_claim_failure(p_claim_id, 'abandoned', 'executor abandoned');
END;
$$;

CREATE OR REPLACE FUNCTION "public"."admin_fail_bounty_claim"("p_claim_id" "uuid", "p_note" "text" DEFAULT NULL::"text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_claim public.bounty_claims;
  v_bounty public.bounties;
BEGIN
  IF NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'admin only';
  END IF;
  SELECT c.* INTO v_claim FROM public.bounty_claims c WHERE c.id = p_claim_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim not found';
  END IF;
  SELECT * INTO v_bounty FROM public.bounties WHERE id = v_claim.bounty_id;
  IF NOT public.policy_work_group_accessible(v_bounty.group_id) THEN
    RAISE EXCEPTION 'group not accessible';
  END IF;
  PERFORM public._finalize_bounty_claim_failure(
    p_claim_id, 'failed', COALESCE(NULLIF(trim(p_note), ''), 'admin marked incomplete')
  );
END;
$$;

CREATE OR REPLACE FUNCTION "public"."assign_device_to_executor"("p_device_id" "text", "p_executor_id" "uuid") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
  v_owner uuid;
  v_id uuid;
BEGIN
  IF NOT public.has_profile_role('device_operator') THEN
    RAISE EXCEPTION 'device_operator only';
  END IF;
  SELECT d.user_id INTO v_owner FROM public.devices d WHERE d.device_id = p_device_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'device not found';
  END IF;
  IF v_owner <> auth.uid() THEN
    RAISE EXCEPTION 'only owner device_operator can assign this device';
  END IF;
  v_group := public.user_active_group_id();
  IF v_group IS NULL THEN
    RAISE EXCEPTION 'no active work group';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles p
    JOIN public.group_members gm ON gm.user_id = p.id
    WHERE p.id = p_executor_id
      AND 'collection_executor' = ANY(COALESCE(p.roles, ARRAY[p.role]))
      AND gm.group_id = v_group
      AND gm.membership_status = 'active'
  ) THEN
    RAISE EXCEPTION 'executor must be active collection_executor in your group';
  END IF;
  UPDATE public.device_executor_assignments
  SET status = 'revoked', revoked_at = now()
  WHERE device_id = p_device_id AND status = 'active';
  INSERT INTO public.device_executor_assignments (group_id, device_id, executor_id, assigned_by, status)
  VALUES (v_group, p_device_id, p_executor_id, auth.uid(), 'active')
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."batch_generate_scene_tasks_for_group"("p_group_id" "uuid") RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  n int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;
  IF NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.scene_tasks (title, description, status, group_id, scenario_position_id, created_by)
  SELECT
    format('【%s】场景采集任务', sp.title),
    concat_ws(
      E'\n\n',
      '本任务由后台按场景岗位批量生成（草稿）；发布后仅在该岗位下与甲方业务大类匹配生成子任务。',
      CASE
        WHEN coalesce(trim(sp.process_description), '') <> '' THEN '岗位说明：' || trim(sp.process_description)
        ELSE NULL
      END,
      '厂区：' || trim(both ' ' FROM concat_ws(
        ' ',
        nullif(trim(sp.address_province), ''),
        nullif(trim(sp.address_city), ''),
        nullif(trim(sp.address_district), '')
      ))
        || CASE
          WHEN coalesce(trim(sp.address_detail), '') <> '' THEN ' ' || trim(sp.address_detail)
          ELSE ''
        END
    ),
    'draft',
    p_group_id,
    sp.id,
    auth.uid()
  FROM public.scenario_positions sp
  WHERE sp.group_id = p_group_id
    AND NOT EXISTS (
      SELECT 1
      FROM public.scene_tasks st
      WHERE st.group_id = p_group_id
        AND st.scenario_position_id = sp.id
    );

  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."checkout_device_for_claim"("p_claim_id" "uuid", "p_device_id" "text") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
  v_claim public.bounty_claims;
  v_bounty public.bounties;
  v_id uuid;
BEGIN
  v_group := public._assert_operator_in_claim_group(p_claim_id);
  SELECT * INTO v_claim FROM public.bounty_claims WHERE id = p_claim_id FOR UPDATE;
  IF NOT FOUND OR v_claim.status <> 'active' THEN
    RAISE EXCEPTION 'claim not active';
  END IF;
  IF v_claim.device_returned_at IS NOT NULL THEN
    RAISE EXCEPTION 'device already returned for this claim';
  END IF;
  SELECT * INTO v_bounty FROM public.bounties WHERE id = v_claim.bounty_id;
  IF EXISTS (
    SELECT 1 FROM public.device_executor_assignments a
    WHERE a.bounty_claim_id = p_claim_id AND a.status = 'active'
  ) THEN
    RAISE EXCEPTION 'claim already has checked-out device';
  END IF;
  IF NOT public._device_is_assignable(p_device_id, v_group, v_bounty.id) THEN
    RAISE EXCEPTION 'device not assignable (type, status, or already in use)';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles p
    JOIN public.group_members gm ON gm.user_id = p.id
    WHERE p.id = v_claim.executor_id
      AND 'collection_executor' = ANY(COALESCE(p.roles, ARRAY[p.role]))
      AND gm.group_id = v_group
      AND gm.membership_status = 'active'
  ) THEN
    RAISE EXCEPTION 'executor not active in group';
  END IF;
  INSERT INTO public.device_executor_assignments (
    group_id, device_id, executor_id, assigned_by, status, bounty_claim_id
  )
  VALUES (
    v_group, p_device_id, v_claim.executor_id, auth.uid(), 'active', p_claim_id
  )
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."claim_bounty"("p_bounty_id" "uuid", "p_hours" integer) RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_bounty public.bounties;
  v_stats public.executor_stats;
  v_tier public.executor_tiers;
  v_claim_id uuid;
  v_due timestamptz;
  v_today date;
  v_claimed_today integer;
  v_daily_cap integer;
  v_per_slot integer;
BEGIN
  IF NOT public.has_profile_role('collection_executor') THEN
    RAISE EXCEPTION 'collection_executor only';
  END IF;
  IF p_hours IS NULL OR p_hours <= 0 THEN
    RAISE EXCEPTION 'hours must be positive';
  END IF;
  PERFORM public.process_overdue_bounty_claims();
  SELECT * INTO v_bounty FROM public.bounties WHERE id = p_bounty_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'bounty not found';
  END IF;
  IF v_bounty.status <> 'open' THEN
    RAISE EXCEPTION 'bounty not open for claims';
  END IF;
  IF NOT public.policy_work_group_accessible(v_bounty.group_id) THEN
    RAISE EXCEPTION 'group not accessible';
  END IF;
  IF p_hours > v_bounty.remaining_hours THEN
    RAISE EXCEPTION 'insufficient remaining hours';
  END IF;
  v_stats := public._ensure_executor_stats(auth.uid());
  SELECT t.* INTO v_tier FROM public.executor_tiers t WHERE t.tier_id = v_stats.tier_id;
  IF v_stats.active_claim_count >= v_tier.max_concurrent_claims THEN
    RAISE EXCEPTION 'concurrent claim limit reached (%)', v_tier.max_concurrent_claims;
  END IF;
  v_per_slot := public.bounty_hours_per_slot_per_day();
  v_today := (now() AT TIME ZONE 'Asia/Shanghai')::date;
  v_claimed_today := public.executor_claimed_hours_on_date(auth.uid(), v_today);
  v_daily_cap := v_tier.max_concurrent_claims * v_per_slot;
  IF v_claimed_today + p_hours > v_daily_cap THEN
    RAISE EXCEPTION
      'daily claim limit exceeded: claimed % h today, requesting % h, limit % h (% slots x % h/day per slot)',
      v_claimed_today, p_hours, v_daily_cap, v_tier.max_concurrent_claims, v_per_slot;
  END IF;
  v_due := now() + (v_bounty.completion_days || ' days')::interval;
  INSERT INTO public.bounty_claims (bounty_id, executor_id, claimed_hours, due_at)
  VALUES (p_bounty_id, auth.uid(), p_hours, v_due)
  RETURNING id INTO v_claim_id;
  UPDATE public.bounties
  SET remaining_hours = remaining_hours - p_hours,
      updated_at = now(),
      status = CASE WHEN remaining_hours - p_hours <= 0 THEN 'fulfilled' ELSE status END
  WHERE id = p_bounty_id;
  UPDATE public.executor_stats
  SET active_claim_count = active_claim_count + 1, updated_at = now()
  WHERE user_id = auth.uid();
  RETURN v_claim_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."clock_in_collection_shift"("p_shift_id" "uuid") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_shift public.collection_shifts;
  v_sess_id uuid;
BEGIN
  IF NOT public.has_profile_role('collection_executor') THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  SELECT * INTO v_shift FROM public.collection_shifts WHERE id = p_shift_id FOR UPDATE;
  IF NOT FOUND OR v_shift.status <> 'published' THEN
    RAISE EXCEPTION 'shift not available';
  END IF;
  IF v_shift.executor_id <> auth.uid() THEN
    RAISE EXCEPTION 'not your shift';
  END IF;
  IF NOT public.policy_work_group_accessible(v_shift.group_id) THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.collection_shift_clock_sessions s
    WHERE s.shift_id = p_shift_id AND s.clock_out_at IS NULL
  ) THEN
    RAISE EXCEPTION 'already clocked in';
  END IF;
  INSERT INTO public.collection_shift_clock_sessions (shift_id, executor_id)
  VALUES (p_shift_id, auth.uid())
  RETURNING id INTO v_sess_id;
  RETURN jsonb_build_object('session_id', v_sess_id, 'clock_in_at', now());
END;
$$;

CREATE OR REPLACE FUNCTION "public"."clock_out_collection_shift"("p_shift_id" "uuid") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_shift public.collection_shifts;
  v_sess public.collection_shift_clock_sessions;
BEGIN
  IF NOT public.has_profile_role('collection_executor') THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  SELECT * INTO v_shift FROM public.collection_shifts WHERE id = p_shift_id;
  IF NOT FOUND OR v_shift.executor_id <> auth.uid() THEN
    RAISE EXCEPTION 'not your shift';
  END IF;
  SELECT * INTO v_sess
  FROM public.collection_shift_clock_sessions s
  WHERE s.shift_id = p_shift_id AND s.clock_out_at IS NULL
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'not clocked in';
  END IF;
  UPDATE public.collection_shift_clock_sessions
  SET clock_out_at = now()
  WHERE id = v_sess.id;
  RETURN jsonb_build_object('session_id', v_sess.id, 'clock_out_at', now());
END;
$$;

CREATE OR REPLACE FUNCTION "public"."close_bounty"("p_bounty_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_bounty public.bounties;
BEGIN
  IF NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'admin only';
  END IF;
  SELECT * INTO v_bounty FROM public.bounties WHERE id = p_bounty_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'bounty not found';
  END IF;
  IF NOT public.policy_work_group_accessible(v_bounty.group_id) THEN
    RAISE EXCEPTION 'group not accessible';
  END IF;
  UPDATE public.bounties
  SET status = 'closed', closed_at = now(), updated_at = now()
  WHERE id = p_bounty_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."complete_bounty_claim"("p_claim_id" "uuid", "p_executed_hours" integer) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF public.has_profile_role('collection_executor') THEN
    RAISE EXCEPTION '任务完成须由设备运维员审核，执行员无法自行标记完成';
  END IF;
  IF NOT public.has_any_profile_role(ARRAY['admin', 'device_operator']) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  IF public.has_profile_role('device_operator') THEN
    PERFORM public.operator_approve_bounty_claim(p_claim_id, p_executed_hours);
    RETURN;
  END IF;
  PERFORM public._complete_bounty_claim_core(p_claim_id, p_executed_hours, 'admin approved');
END;
$$;

CREATE OR REPLACE FUNCTION "public"."create_collection_shift"("p_group_id" "uuid", "p_scenario_position_id" "uuid", "p_executor_id" "uuid", "p_device_count" integer, "p_scheduled_start" timestamp with time zone DEFAULT NULL::timestamp with time zone, "p_scheduled_end" timestamp with time zone DEFAULT NULL::timestamp with time zone, "p_note" "text" DEFAULT NULL::"text") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_role text;
  v_id uuid;
BEGIN
  v_role := public.current_profile_role();
  IF v_role NOT IN ('admin', 'scene_operator') THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  IF v_role <> 'admin' AND NOT public.policy_work_group_accessible(p_group_id) THEN
    RAISE EXCEPTION 'not allowed';
  END IF;
  IF p_device_count IS NULL OR p_device_count < 1 OR p_device_count > 100 THEN
    RAISE EXCEPTION 'device_count must be between 1 and 100';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.scenario_positions sp
    WHERE sp.id = p_scenario_position_id AND sp.group_id = p_group_id
  ) THEN
    RAISE EXCEPTION 'scenario position not in group';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.group_members gm
    WHERE gm.group_id = p_group_id
      AND gm.user_id = p_executor_id
      AND gm.membership_status = 'active'
  ) THEN
    RAISE EXCEPTION 'executor must be active group member';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = p_executor_id AND 'collection_executor' = ANY(COALESCE(p.roles, ARRAY[p.role]))
  ) THEN
    RAISE EXCEPTION 'executor must be collection_executor role';
  END IF;

  INSERT INTO public.collection_shifts (
    group_id, scenario_position_id, executor_id, device_count,
    status, note, scheduled_start, scheduled_end, created_by
  )
  VALUES (
    p_group_id, p_scenario_position_id, p_executor_id, p_device_count,
    'draft', NULLIF(trim(p_note), ''), p_scheduled_start, p_scheduled_end, auth.uid()
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.current_profile_role() RETURNS "text"
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION "public"."operator_approve_bounty_claim"("p_claim_id" "uuid", "p_confirmed_hours" integer) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
BEGIN
  IF NOT public.has_any_profile_role(ARRAY['device_operator', 'admin']) THEN
    RAISE EXCEPTION 'device_operator or admin only';
  END IF;
  v_group := public._bounty_group_id_for_claim(p_claim_id);
  IF v_group IS NULL OR NOT public.policy_work_group_accessible(v_group) THEN
    RAISE EXCEPTION 'claim not in accessible group';
  END IF;
  IF public.has_profile_role('device_operator')
     AND NOT public._profile_is_device_operator_in_group(auth.uid(), v_group) THEN
    RAISE EXCEPTION 'not a device operator in this group';
  END IF;
  PERFORM public._complete_bounty_claim_core(
    p_claim_id, p_confirmed_hours, 'operator approved'
  );
END;
$$;

CREATE OR REPLACE FUNCTION "public"."operator_reject_bounty_claim"("p_claim_id" "uuid", "p_note" "text" DEFAULT NULL::"text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
BEGIN
  IF NOT public.has_any_profile_role(ARRAY['device_operator', 'admin']) THEN
    RAISE EXCEPTION 'device_operator or admin only';
  END IF;
  v_group := public._bounty_group_id_for_claim(p_claim_id);
  IF v_group IS NULL OR NOT public.policy_work_group_accessible(v_group) THEN
    RAISE EXCEPTION 'claim not in accessible group';
  END IF;
  PERFORM public._finalize_bounty_claim_failure(
    p_claim_id, 'failed', COALESCE(NULLIF(trim(p_note), ''), 'operator rejected')
  );
END;
$$;

CREATE OR REPLACE FUNCTION "public"."publish_bounty"("p_group_id" "uuid", "p_title" "text", "p_total_hours" integer, "p_hourly_rate" numeric, "p_completion_days" integer, "p_description" "text" DEFAULT NULL::"text", "p_points_per_hour" numeric DEFAULT 1, "p_assigned_operator_id" "uuid" DEFAULT NULL::"uuid", "p_party_demand_ids" "uuid"[] DEFAULT NULL::"uuid"[]) RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_id uuid;
  v_pd uuid;
BEGIN
  IF NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'admin only';
  END IF;
  IF NOT public.policy_work_group_accessible(p_group_id) THEN
    RAISE EXCEPTION 'group not accessible';
  END IF;
  IF p_assigned_operator_id IS NULL THEN
    RAISE EXCEPTION 'assigned operator required';
  END IF;
  IF NOT public._profile_is_device_operator_in_group(p_assigned_operator_id, p_group_id) THEN
    RAISE EXCEPTION 'assigned operator must be active device_operator in this group';
  END IF;
  IF p_party_demand_ids IS NULL OR array_length(p_party_demand_ids, 1) IS NULL THEN
    RAISE EXCEPTION 'at least one party demand (device type) required';
  END IF;
  FOREACH v_pd IN ARRAY p_party_demand_ids LOOP
    IF NOT EXISTS (
      SELECT 1 FROM public.party_demands pd
      WHERE pd.id = v_pd AND pd.group_id = p_group_id
    ) THEN
      RAISE EXCEPTION 'party demand % not in group', v_pd;
    END IF;
  END LOOP;
  IF p_total_hours IS NULL OR p_total_hours <= 0 THEN
    RAISE EXCEPTION 'total_hours must be positive';
  END IF;
  IF p_completion_days NOT IN (1, 2, 3) THEN
    RAISE EXCEPTION 'completion_days must be 1, 2, or 3';
  END IF;
  IF p_points_per_hour IS NULL OR p_points_per_hour <= 0 THEN
    p_points_per_hour := 1;
  END IF;
  INSERT INTO public.bounties (
    group_id, title, description, total_hours, remaining_hours,
    hourly_rate, completion_days, points_per_hour, status, created_by, assigned_operator_id
  )
  VALUES (
    p_group_id,
    COALESCE(NULLIF(trim(p_title), ''), '悬赏单'),
    NULLIF(trim(p_description), ''),
    p_total_hours,
    p_total_hours,
    COALESCE(p_hourly_rate, 0),
    p_completion_days,
    p_points_per_hour,
    'open',
    auth.uid(),
    p_assigned_operator_id
  )
  RETURNING id INTO v_id;
  FOREACH v_pd IN ARRAY p_party_demand_ids LOOP
    INSERT INTO public.bounty_allowed_party_demands (bounty_id, party_demand_id)
    VALUES (v_id, v_pd)
    ON CONFLICT DO NOTHING;
  END LOOP;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."register_device_data_hours"("p_device_id" "text", "p_registered_hours" numeric, "p_bounty_claim_id" "uuid" DEFAULT NULL::"uuid", "p_note" "text" DEFAULT NULL::"text") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_group uuid;
  v_owner uuid;
  v_id uuid;
BEGIN
  IF NOT public.has_profile_role('device_operator') THEN
    RAISE EXCEPTION 'device_operator only';
  END IF;
  IF p_registered_hours IS NULL OR p_registered_hours <= 0 THEN
    RAISE EXCEPTION 'hours must be positive';
  END IF;
  SELECT d.user_id INTO v_owner FROM public.devices d WHERE d.device_id = p_device_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'device not found';
  END IF;
  IF v_owner <> auth.uid() THEN
    RAISE EXCEPTION 'only owner device_operator can register hours';
  END IF;
  v_group := public.user_active_group_id();
  IF v_group IS NULL THEN
    RAISE EXCEPTION 'no active work group';
  END IF;
  IF p_bounty_claim_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.bounty_claims c
      JOIN public.bounties b ON b.id = c.bounty_id
      WHERE c.id = p_bounty_claim_id AND b.group_id = v_group
    ) THEN
      RAISE EXCEPTION 'claim not in your group';
    END IF;
  END IF;
  INSERT INTO public.device_data_hour_logs (
    group_id, device_id, bounty_claim_id, registered_hours, registered_by, note
  )
  VALUES (
    v_group, p_device_id, p_bounty_claim_id,
    p_registered_hours, auth.uid(), NULLIF(trim(p_note), '')
  )
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."revoke_device_assignment"("p_assignment_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_row public.device_executor_assignments;
BEGIN
  IF NOT public.has_profile_role('device_operator') THEN
    RAISE EXCEPTION 'device_operator only';
  END IF;
  SELECT * INTO v_row FROM public.device_executor_assignments WHERE id = p_assignment_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'assignment not found';
  END IF;
  IF v_row.assigned_by <> auth.uid() AND NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'only assigner can revoke';
  END IF;
  UPDATE public.device_executor_assignments
  SET status = 'revoked', revoked_at = now()
  WHERE id = p_assignment_id;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."sync_scene_task_assignments"("p_group_id" "uuid") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;
  IF NOT public.policy_work_group_accessible(p_group_id) AND NOT public.has_profile_role('admin') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.scene_task_assignments sta
  USING public.scene_tasks st
  WHERE sta.scene_task_id = st.id
    AND st.group_id = p_group_id
    AND st.status <> 'published';

  DELETE FROM public.scene_task_assignments sta
  USING public.scene_tasks st, public.party_demands d, public.scenario_positions p
  WHERE sta.scene_task_id = st.id
    AND sta.party_demand_id = d.id
    AND sta.scenario_position_id = p.id
    AND st.group_id = p_group_id
    AND st.status = 'published'
    AND NOT public.scene_categories_overlap(d.scene_categories, p.scene_categories);

  INSERT INTO public.scene_task_assignments (scene_task_id, scenario_position_id, party_demand_id, max_hours_cap)
  SELECT st.id, p.id, d.id, d.max_hours_per_scene
  FROM public.scene_tasks st
  CROSS JOIN public.party_demands d
  INNER JOIN public.scenario_positions p
    ON p.group_id = p_group_id
    AND (st.scenario_position_id IS NULL OR p.id = st.scenario_position_id)
  WHERE st.group_id = p_group_id
    AND st.status = 'published'
    AND d.group_id = p_group_id
    AND public.scene_categories_overlap(d.scene_categories, p.scene_categories)
  ON CONFLICT (scene_task_id, scenario_position_id, party_demand_id) DO NOTHING;

  UPDATE public.scene_task_assignments sta
  SET max_hours_cap = d.max_hours_per_scene
  FROM public.party_demands d, public.scene_tasks st
  WHERE sta.party_demand_id = d.id
    AND sta.scene_task_id = st.id
    AND st.group_id = p_group_id
    AND d.group_id = p_group_id;
END;
$$;

NOTIFY pgrst, 'reload schema';
