-- AUTO-GENERATED by scripts/generate_multi_role_patch.py — do not edit by hand
-- RLS: current_profile_role() → has_profile_role / has_any_profile_role

DROP POLICY IF EXISTS "admin_kpis_delete_admin" ON "public"."admin_kpis";
CREATE POLICY "admin_kpis_delete_admin" ON "public"."admin_kpis" FOR DELETE TO "authenticated" USING ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "admin_kpis_insert_admin" ON "public"."admin_kpis";
CREATE POLICY "admin_kpis_insert_admin" ON "public"."admin_kpis" FOR INSERT TO "authenticated" WITH CHECK ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "admin_kpis_update_admin" ON "public"."admin_kpis";
CREATE POLICY "admin_kpis_update_admin" ON "public"."admin_kpis" FOR UPDATE TO "authenticated" USING ((public.has_profile_role('admin'))) WITH CHECK ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "admin_messages_delete_admin" ON "public"."admin_messages";
CREATE POLICY "admin_messages_delete_admin" ON "public"."admin_messages" FOR DELETE TO "authenticated" USING ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "admin_messages_write_admin" ON "public"."admin_messages";
CREATE POLICY "admin_messages_write_admin" ON "public"."admin_messages" FOR INSERT TO "authenticated" WITH CHECK ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "bapd_select" ON "public"."bounty_allowed_party_demands";
CREATE POLICY "bapd_select" ON "public"."bounty_allowed_party_demands" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR (EXISTS ( SELECT 1
   FROM "public"."bounties" "b"
  WHERE (("b"."id" = "bounty_allowed_party_demands"."bounty_id") AND "public"."policy_work_group_accessible"("b"."group_id"))))));

DROP POLICY IF EXISTS "bounties_select_group_or_admin" ON "public"."bounties";
CREATE POLICY "bounties_select_group_or_admin" ON "public"."bounties" FOR SELECT TO "authenticated" USING (("public"."policy_work_group_accessible"("group_id") OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "bounty_claims_select_executor_admin_or_operator" ON "public"."bounty_claims";
CREATE POLICY "bounty_claims_select_executor_admin_or_operator" ON "public"."bounty_claims" FOR SELECT TO "authenticated" USING ((("executor_id" = "auth"."uid"()) OR (public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND "public"."policy_work_group_accessible"("public"."_bounty_group_id_for_claim"("id")))));

DROP POLICY IF EXISTS "collection_req_delete_scene_or_admin" ON "public"."collection_requirements";
CREATE POLICY "collection_req_delete_scene_or_admin" ON "public"."collection_requirements" FOR DELETE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "t"
  WHERE (("t"."id" = "collection_requirements"."scene_task_id") AND ("t"."created_by" = "auth"."uid"())))))));

DROP POLICY IF EXISTS "collection_req_insert_scene_or_admin" ON "public"."collection_requirements";
CREATE POLICY "collection_req_insert_scene_or_admin" ON "public"."collection_requirements" FOR INSERT TO "authenticated" WITH CHECK (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "t"
  WHERE (("t"."id" = "collection_requirements"."scene_task_id") AND ("t"."created_by" = "auth"."uid"())))) AND ("created_by" = "auth"."uid"()))));

DROP POLICY IF EXISTS "collection_req_select" ON "public"."collection_requirements";
CREATE POLICY "collection_req_select" ON "public"."collection_requirements" FOR SELECT TO "authenticated" USING (((public.has_any_profile_role(ARRAY['admin', 'scene_operator'])) OR ((public.has_profile_role('collection_executor')) AND (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "t"
  WHERE (("t"."id" = "collection_requirements"."scene_task_id") AND ("t"."status" = 'published'::"text")))))));

DROP POLICY IF EXISTS "collection_req_update_scene_or_admin" ON "public"."collection_requirements";
CREATE POLICY "collection_req_update_scene_or_admin" ON "public"."collection_requirements" FOR UPDATE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "t"
  WHERE (("t"."id" = "collection_requirements"."scene_task_id") AND ("t"."created_by" = "auth"."uid"()))))))) WITH CHECK (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "t"
  WHERE (("t"."id" = "collection_requirements"."scene_task_id") AND ("t"."created_by" = "auth"."uid"())))))));

DROP POLICY IF EXISTS "collection_shift_clock_select" ON "public"."collection_shift_clock_sessions";
CREATE POLICY "collection_shift_clock_select" ON "public"."collection_shift_clock_sessions" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."collection_shifts" "cs"
  WHERE (("cs"."id" = "collection_shift_clock_sessions"."shift_id") AND ((public.has_profile_role('admin')) OR ("public"."policy_work_group_accessible"("cs"."group_id") AND ((public.has_profile_role('scene_operator')) OR ((public.has_profile_role('collection_executor')) AND ("cs"."executor_id" = "auth"."uid"())))))))));

DROP POLICY IF EXISTS "collection_shift_devices_select" ON "public"."collection_shift_devices";
CREATE POLICY "collection_shift_devices_select" ON "public"."collection_shift_devices" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."collection_shifts" "cs"
  WHERE (("cs"."id" = "collection_shift_devices"."shift_id") AND ((public.has_profile_role('admin')) OR ("public"."policy_work_group_accessible"("cs"."group_id") AND ((public.has_profile_role('scene_operator')) OR ((public.has_profile_role('collection_executor')) AND ("cs"."executor_id" = "auth"."uid"())))))))));

DROP POLICY IF EXISTS "collection_shifts_select" ON "public"."collection_shifts";
CREATE POLICY "collection_shifts_select" ON "public"."collection_shifts" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR ("public"."policy_work_group_accessible"("group_id") AND ((public.has_profile_role('scene_operator')) OR ((public.has_profile_role('collection_executor')) AND ("executor_id" = "auth"."uid"()) AND ("status" = ANY (ARRAY['published'::"text", 'closed'::"text"])))))));

DROP POLICY IF EXISTS "ddhl_select_group" ON "public"."device_data_hour_logs";
CREATE POLICY "ddhl_select_group" ON "public"."device_data_hour_logs" FOR SELECT TO "authenticated" USING ((("registered_by" = "auth"."uid"()) OR (public.has_profile_role('admin')) OR ((public.has_any_profile_role(ARRAY['device_operator', 'collection_executor'])) AND "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "dea_select_group" ON "public"."device_executor_assignments";
CREATE POLICY "dea_select_group" ON "public"."device_executor_assignments" FOR SELECT TO "authenticated" USING ((("executor_id" = "auth"."uid"()) OR ("assigned_by" = "auth"."uid"()) OR (public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "devices_delete_ops_or_admin" ON "public"."devices";
CREATE POLICY "devices_delete_ops_or_admin" ON "public"."devices" FOR DELETE TO "authenticated" USING ((((public.has_profile_role('admin')) AND "public"."device_visible_to_fleet_roles"("user_id")) OR (("user_id" = "auth"."uid"()) AND (public.has_profile_role('device_operator')))));

DROP POLICY IF EXISTS "devices_insert_ops_or_admin" ON "public"."devices";
CREATE POLICY "devices_insert_ops_or_admin" ON "public"."devices" FOR INSERT TO "authenticated" WITH CHECK ((("user_id" = "auth"."uid"()) AND (public.has_any_profile_role(ARRAY['admin', 'device_operator']))));

DROP POLICY IF EXISTS "devices_select" ON "public"."devices";
CREATE POLICY "devices_select" ON "public"."devices" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR ((public.has_any_profile_role(ARRAY['admin', 'collection_executor'])) AND "public"."device_visible_to_fleet_roles"("user_id"))));

DROP POLICY IF EXISTS "devices_update_ops_or_admin" ON "public"."devices";
CREATE POLICY "devices_update_ops_or_admin" ON "public"."devices" FOR UPDATE TO "authenticated" USING ((((public.has_profile_role('admin')) AND "public"."device_visible_to_fleet_roles"("user_id")) OR (("user_id" = "auth"."uid"()) AND (public.has_profile_role('device_operator'))))) WITH CHECK ((((public.has_profile_role('admin')) AND "public"."device_visible_to_fleet_roles"("user_id")) OR (("user_id" = "auth"."uid"()) AND (public.has_profile_role('device_operator')))));

DROP POLICY IF EXISTS "executor_point_ledger_select_own_or_admin" ON "public"."executor_point_ledger";
CREATE POLICY "executor_point_ledger_select_own_or_admin" ON "public"."executor_point_ledger" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "executor_settlement_lines_select" ON "public"."executor_settlement_lines";
CREATE POLICY "executor_settlement_lines_select" ON "public"."executor_settlement_lines" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "executor_stats_select_own_or_admin" ON "public"."executor_stats";
CREATE POLICY "executor_stats_select_own_or_admin" ON "public"."executor_stats" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "executor_wallet_ledger_select_own_or_admin" ON "public"."executor_wallet_ledger";
CREATE POLICY "executor_wallet_ledger_select_own_or_admin" ON "public"."executor_wallet_ledger" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "executor_wallets_select_own_or_admin" ON "public"."executor_wallets";
CREATE POLICY "executor_wallets_select_own_or_admin" ON "public"."executor_wallets" FOR SELECT TO "authenticated" USING ((("user_id" = "auth"."uid"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "gm_admin_update_any" ON "public"."group_members";
CREATE POLICY "gm_admin_update_any" ON "public"."group_members" FOR UPDATE TO "authenticated" USING ((public.has_profile_role('admin'))) WITH CHECK ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "gm_select" ON "public"."group_members";
CREATE POLICY "gm_select" ON "public"."group_members" FOR SELECT TO "authenticated" USING (("public"."policy_work_group_accessible"("group_id") OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "gt_delete_own_or_admin" ON "public"."group_topics";
CREATE POLICY "gt_delete_own_or_admin" ON "public"."group_topics" FOR DELETE TO "authenticated" USING (((("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"())) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "gt_select_scope" ON "public"."group_topics";
CREATE POLICY "gt_select_scope" ON "public"."group_topics" FOR SELECT TO "authenticated" USING ((("group_id" = "public"."user_active_group_id"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "gt_update_own_or_admin" ON "public"."group_topics";
CREATE POLICY "gt_update_own_or_admin" ON "public"."group_topics" FOR UPDATE TO "authenticated" USING (((("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"())) OR (public.has_profile_role('admin')))) WITH CHECK (((public.has_profile_role('admin')) OR (("group_id" = "public"."user_active_group_id"()) AND ("created_by" = "auth"."uid"()))));

DROP POLICY IF EXISTS "mtd_delete" ON "public"."manual_tracked_devices";
CREATE POLICY "mtd_delete" ON "public"."manual_tracked_devices" FOR DELETE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND ("group_id" IS NOT NULL) AND ("group_id" = "public"."user_active_group_id"()))));

DROP POLICY IF EXISTS "mtd_insert" ON "public"."manual_tracked_devices";
CREATE POLICY "mtd_insert" ON "public"."manual_tracked_devices" FOR INSERT TO "authenticated" WITH CHECK ((("created_by" = "auth"."uid"()) AND (public.has_any_profile_role(ARRAY['admin', 'device_operator'])) AND ("group_id" IS NOT NULL) AND ((public.has_profile_role('admin')) OR ("group_id" = "public"."user_active_group_id"()))));

DROP POLICY IF EXISTS "mtd_select" ON "public"."manual_tracked_devices";
CREATE POLICY "mtd_select" ON "public"."manual_tracked_devices" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR (("group_id" IS NOT NULL) AND ("group_id" = "public"."user_active_group_id"()))));

DROP POLICY IF EXISTS "mtd_update" ON "public"."manual_tracked_devices";
CREATE POLICY "mtd_update" ON "public"."manual_tracked_devices" FOR UPDATE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND ("group_id" IS NOT NULL) AND ("group_id" = "public"."user_active_group_id"())))) WITH CHECK (((public.has_profile_role('admin')) OR ((public.has_profile_role('device_operator')) AND ("group_id" IS NOT NULL) AND ("group_id" = "public"."user_active_group_id"()))));

DROP POLICY IF EXISTS "pd_delete" ON "public"."party_demands";
CREATE POLICY "pd_delete" ON "public"."party_demands" FOR DELETE TO "authenticated" USING ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "pd_insert" ON "public"."party_demands";
CREATE POLICY "pd_insert" ON "public"."party_demands" FOR INSERT TO "authenticated" WITH CHECK ((public.has_profile_role('admin') AND ("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"())));

DROP POLICY IF EXISTS "pd_select" ON "public"."party_demands";
CREATE POLICY "pd_select" ON "public"."party_demands" FOR SELECT TO "authenticated" USING ((("group_id" = "public"."user_active_group_id"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "pd_update" ON "public"."party_demands";
CREATE POLICY "pd_update" ON "public"."party_demands" FOR UPDATE TO "authenticated" USING ((public.has_profile_role('admin'))) WITH CHECK ((public.has_profile_role('admin')));

DROP POLICY IF EXISTS "profiles_admin_update" ON "public"."profiles";
CREATE POLICY "profiles_admin_update" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ((public.has_profile_role('admin'))) WITH CHECK (true);

DROP POLICY IF EXISTS "profiles_select_self_or_admin" ON "public"."profiles";
CREATE POLICY "profiles_select_self_or_admin" ON "public"."profiles" FOR SELECT TO "authenticated" USING ((("id" = "auth"."uid"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "scene_macro_sites_delete" ON "public"."scene_macro_sites";
CREATE POLICY "scene_macro_sites_delete" ON "public"."scene_macro_sites" FOR DELETE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "scene_macro_sites_insert" ON "public"."scene_macro_sites";
CREATE POLICY "scene_macro_sites_insert" ON "public"."scene_macro_sites" FOR INSERT TO "authenticated" WITH CHECK ((("created_by" = "auth"."uid"()) AND (public.has_any_profile_role(ARRAY['admin', 'scene_operator'])) AND ((public.has_profile_role('admin')) OR "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "scene_macro_sites_select" ON "public"."scene_macro_sites";
CREATE POLICY "scene_macro_sites_select" ON "public"."scene_macro_sites" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR ("public"."policy_work_group_accessible"("group_id") AND (public.has_any_profile_role(ARRAY['scene_operator', 'collection_executor'])))));

DROP POLICY IF EXISTS "scene_macro_sites_update" ON "public"."scene_macro_sites";
CREATE POLICY "scene_macro_sites_update" ON "public"."scene_macro_sites" FOR UPDATE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND "public"."policy_work_group_accessible"("group_id")))) WITH CHECK (true);

DROP POLICY IF EXISTS "scene_tasks_delete_draft_in_group_or_admin" ON "public"."scene_tasks";
CREATE POLICY "scene_tasks_delete_draft_in_group_or_admin" ON "public"."scene_tasks" FOR DELETE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND ("status" = 'draft'::"text") AND ("group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("group_id"))));

DROP POLICY IF EXISTS "scene_tasks_insert_admin_only" ON "public"."scene_tasks";
CREATE POLICY "scene_tasks_insert_admin_only" ON "public"."scene_tasks" FOR INSERT TO "authenticated" WITH CHECK ((("created_by" = "auth"."uid"()) AND (public.has_profile_role('admin')) AND ("group_id" IS NOT NULL)));

DROP POLICY IF EXISTS "scene_tasks_select" ON "public"."scene_tasks";
CREATE POLICY "scene_tasks_select" ON "public"."scene_tasks" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR (("group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("group_id") AND ((public.has_profile_role('scene_operator')) OR ((public.has_profile_role('collection_executor')) AND ("status" = 'published'::"text"))))));

DROP POLICY IF EXISTS "scene_tasks_update_group_scope" ON "public"."scene_tasks";
CREATE POLICY "scene_tasks_update_group_scope" ON "public"."scene_tasks" FOR UPDATE TO "authenticated" USING (((public.has_profile_role('admin')) OR ((public.has_profile_role('scene_operator')) AND ("group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("group_id")))) WITH CHECK (true);

DROP POLICY IF EXISTS "sp_delete" ON "public"."scenario_positions";
CREATE POLICY "sp_delete" ON "public"."scenario_positions" FOR DELETE TO "authenticated" USING (((("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"())) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "sp_insert" ON "public"."scenario_positions";
CREATE POLICY "sp_insert" ON "public"."scenario_positions" FOR INSERT TO "authenticated" WITH CHECK ((("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"()) AND (public.has_any_profile_role(ARRAY['scene_operator', 'admin']))));

DROP POLICY IF EXISTS "sp_select" ON "public"."scenario_positions";
CREATE POLICY "sp_select" ON "public"."scenario_positions" FOR SELECT TO "authenticated" USING ((("group_id" = "public"."user_active_group_id"()) OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "sp_update" ON "public"."scenario_positions";
CREATE POLICY "sp_update" ON "public"."scenario_positions" FOR UPDATE TO "authenticated" USING (((("created_by" = "auth"."uid"()) AND ("group_id" = "public"."user_active_group_id"()) AND (public.has_any_profile_role(ARRAY['scene_operator', 'admin']))) OR (public.has_profile_role('admin')))) WITH CHECK (((public.has_profile_role('admin')) OR (("group_id" = "public"."user_active_group_id"()) AND ("created_by" = "auth"."uid"()))));

DROP POLICY IF EXISTS "sta_select" ON "public"."scene_task_assignments";
CREATE POLICY "sta_select" ON "public"."scene_task_assignments" FOR SELECT TO "authenticated" USING (((public.has_profile_role('admin')) OR (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "st"
  WHERE (("st"."id" = "scene_task_assignments"."scene_task_id") AND ("st"."group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("st"."group_id"))))));

DROP POLICY IF EXISTS "sta_update_hours" ON "public"."scene_task_assignments";
CREATE POLICY "sta_update_hours" ON "public"."scene_task_assignments" FOR UPDATE TO "authenticated" USING (((public.has_profile_role('admin')) OR (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "st"
  WHERE (("st"."id" = "scene_task_assignments"."scene_task_id") AND ("st"."group_id" IS NOT NULL) AND ("st"."status" = 'published'::"text") AND "public"."policy_work_group_accessible"("st"."group_id") AND (public.has_profile_role('collection_executor'))))) OR (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "st"
  WHERE (("st"."id" = "scene_task_assignments"."scene_task_id") AND ("st"."group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("st"."group_id") AND (public.has_any_profile_role(ARRAY['scene_operator', 'admin']))))))) WITH CHECK (((public.has_profile_role('admin')) OR (EXISTS ( SELECT 1
   FROM "public"."scene_tasks" "st"
  WHERE (("st"."id" = "scene_task_assignments"."scene_task_id") AND ("st"."group_id" IS NOT NULL) AND "public"."policy_work_group_accessible"("st"."group_id"))))));

DROP POLICY IF EXISTS "wg_insert_one_owned" ON "public"."work_groups";
CREATE POLICY "wg_insert_one_owned" ON "public"."work_groups" FOR INSERT TO "authenticated" WITH CHECK (((public.has_profile_role('admin')) AND ("auth"."uid"() = "owner_user_id") AND (NOT "public"."user_owns_any_work_group"())));

DROP POLICY IF EXISTS "wg_select_related" ON "public"."work_groups";
CREATE POLICY "wg_select_related" ON "public"."work_groups" FOR SELECT TO "authenticated" USING (("public"."policy_work_group_accessible"("id") OR (public.has_profile_role('admin'))));

DROP POLICY IF EXISTS "scenario_snap_delete" ON "storage"."objects";
CREATE POLICY "scenario_snap_delete" ON "storage"."objects" FOR DELETE TO "authenticated" USING ((("bucket_id" = 'scenario-workstation-snapshots'::"text") AND ("split_part"("name", '/'::"text", 1) = ("public"."user_active_group_id"())::"text") AND (public.has_any_profile_role(ARRAY['scene_operator', 'admin']))));

DROP POLICY IF EXISTS "scenario_snap_insert" ON "storage"."objects";
CREATE POLICY "scenario_snap_insert" ON "storage"."objects" FOR INSERT TO "authenticated" WITH CHECK ((("bucket_id" = 'scenario-workstation-snapshots'::"text") AND ("split_part"("name", '/'::"text", 1) = ("public"."user_active_group_id"())::"text") AND (public.has_any_profile_role(ARRAY['scene_operator', 'admin']))));

NOTIFY pgrst, 'reload schema';
